title: 夜雨闻曦
subtitle: 躲进小楼成一统，管他冬夏与春秋。
description: 在读大学生
keywords: null
author: pcl
language: zh-CN
timezone: ''

url: http://yeyuwenxi.github.io
root: /

permalink: ':year/:month/:day/:title/'
permalink_defaults: null
pretty_urls:
  trailing_index: true
  trailing_html: true
source_dir: source
public_dir: public
tag_dir: tags
archive_dir: archives
category_dir: categories
code_dir: downloads/code
i18n_dir: ':lang'
skip_render: 
- backups/*
new_post_name: ':title.md'
default_layout: post
titlecase: false
external_link:
  enable: true
  field: site
  exclude: ''
filename_case: 0
render_drafts: false
post_asset_folder: false
relative_link: false
future: true
highlight:
   enable: true
   line_number: true
   auto_detect: true
   tab_replace: ''
   wrap: true
   hljs: false
prismjs:
  enable: true
  preprocess: true
  line_number: true
  tab_replace: ''


# prism_plugin:
#   mode: 'preprocess'    # realtime/preprocess
#   theme: 'tomorrow'
#   line_number: false    # default false
#   custom_css:

index_generator:
  path: ''
  per_page: 9
  order_by: '-date'
default_category: uncategorized
category_map: null
tag_map: null
meta_generator: true
date_format: YYYY-MM-DD
time_format: HH:mm:ss
updated_option: mtime
per_page: 9
pagination_dir: page
include: null
exclude: null
ignore: null
theme:  hexo-theme-matery-master
deploy:
  - type: git
    repo: https://gitee.com/yeyuwenxi/yeyuwenxi.git
    branch: master
  - type: git
    repo: https://github.com/yeyuwenxi/yeyuwenxi.git
    branch: master
search:
  path: search.xml
  field: post
permalink_pinyin:
  enable: true
  separator: '-' # default: '-'

